# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5b969590-9593-4037-ba97-91bb0a832e35";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1DC7-70A2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };






  fileSystems."/mnt/stolenFromSister" = {
    device = "/dev/disk/by-uuid/8f2c41c0-84bb-40ee-a3f8-b1bbd378d5d7";
    fsType = "ext4";                # or "btrfs", "xfs", etc.
      options = [ "nofail" "x-systemd.automount"];         # don't block boot if the disk is missing
  };

  fileSystems."/mnt/OtherStolenDriveFromSister" = {
    device = "/dev/disk/by-uuid/fc16759c-24fc-46d6-99fe-865068605f46";
    fsType = "ext4";                # or "btrfs", "xfs", etc.
      options = [ "nofail" "x-systemd.automount"];         # don't block boot if the disk is missing
  };

  systemd.tmpfiles.rules = [
    "d /mnt/stolenFromSister/jelly/ 0755 starr starr -"
    "d /mnt/OtherStolenDriveFromSister/downloads/ 0755 starr starr -"
  ];





  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
