# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5b969590-9593-4037-ba97-91bb0a832e35";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1DC7-70A2";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/stolenFromSister" = {
    device = "/dev/disk/by-uuid/8f2c41c0-84bb-40ee-a3f8-b1bbd378d5d7";
    fsType = "ext4"; # or "btrfs", "xfs", etc.
    options = [
      "nofail"
      "x-systemd.automount"
    ]; # don't block boot if the disk is missing
  };

  fileSystems."/mnt/OtherStolenDriveFromSister" = {
    device = "/dev/disk/by-uuid/fc16759c-24fc-46d6-99fe-865068605f46";
    fsType = "ext4"; # or "btrfs", "xfs", etc.
    options = [
      "nofail"
      "x-systemd.automount"
    ]; # don't block boot if the disk is missing
  };

  fileSystems."/mnt/disk3" = {
    device = "/dev/disk/by-partuuid/54084a5e-2c7f-4ec9-8ee7-9ede76c79f40";
    fsType = "ext4";
    options = [ "nofail" "x-systemd.automount" ];
  };

  fileSystems."/mnt/disk4" = {
    device = "/dev/disk/by-partuuid/9df16012-ef2f-4091-aa24-632d98e6be51";
    fsType = "ext4";
    options = [ "nofail" "x-systemd.automount" ];
  };

  # fileSystems."/mnt/benjaSteal" = {
  #   device = "mediaslave@deprived.dev:/";
  #   fsType = "sshfs";
  #   options =
  #     [ "nodev" "noatime" "allow_other" "IdentityFile=/root/.ssh/id_ed25519" ];
  # };

  # fileSystems."/mnt/disk5" = {
  #   device = "/dev/disk/by-partuuid/3610155d-6d3d-4be1-9e50-7a638ccbf98c";
  #   fsType = "ext4";
  #   options = [ "nofail" "x-systemd.automount" ];
  # };

  systemd.tmpfiles.rules = [
    "d /mnt/stolenFromSister/jelly/ 0755 starr starr -"
    "d /mnt/OtherStolenDriveFromSister/downloads/ 0755 starr starr -"
  ];

  swapDevices = [ ];
  zramSwap.enable = true;
  hardware.bluetooth.enable = true;

  systemd.network.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
